// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCSk-UgFhyyPDhKJhzR-1kjRM9VWtasoJs',
    appId: '1:13210723636:web:4029af0c416c0b6b72b161',
    messagingSenderId: '13210723636',
    projectId: 'todolist-99416',
    authDomain: 'todolist-99416.firebaseapp.com',
    storageBucket: 'todolist-99416.firebasestorage.app',
    measurementId: 'G-Y2120WV8D4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDYMn4HJdyuDOlcdDMyMzkmU5D7Tfb39Jg',
    appId: '1:13210723636:android:915ccd5d84ff050372b161',
    messagingSenderId: '13210723636',
    projectId: 'todolist-99416',
    storageBucket: 'todolist-99416.firebasestorage.app',
  );
}
